/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DaydreamTestError } from "./daydreamtesterror.js";

/**
 * Default Response
 */
export type CreateStreamInternalServerErrorData = {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;
};

/**
 * Default Response
 */
export class CreateStreamInternalServerError extends DaydreamTestError {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: CreateStreamInternalServerErrorData;

  constructor(
    err: CreateStreamInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;

    this.name = "CreateStreamInternalServerError";
  }
}

/**
 * Default Response
 */
export type CreateStreamBadRequestErrorData = {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;
};

/**
 * Default Response
 */
export class CreateStreamBadRequestError extends DaydreamTestError {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: CreateStreamBadRequestErrorData;

  constructor(
    err: CreateStreamBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;

    this.name = "CreateStreamBadRequestError";
  }
}

/** @internal */
export const CreateStreamInternalServerError$inboundSchema: z.ZodType<
  CreateStreamInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CreateStreamInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CreateStreamInternalServerError$Outbound = {
  success: boolean;
  error: string;
};

/** @internal */
export const CreateStreamInternalServerError$outboundSchema: z.ZodType<
  CreateStreamInternalServerError$Outbound,
  z.ZodTypeDef,
  CreateStreamInternalServerError
> = z.instanceof(CreateStreamInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateStreamInternalServerError$ {
  /** @deprecated use `CreateStreamInternalServerError$inboundSchema` instead. */
  export const inboundSchema = CreateStreamInternalServerError$inboundSchema;
  /** @deprecated use `CreateStreamInternalServerError$outboundSchema` instead. */
  export const outboundSchema = CreateStreamInternalServerError$outboundSchema;
  /** @deprecated use `CreateStreamInternalServerError$Outbound` instead. */
  export type Outbound = CreateStreamInternalServerError$Outbound;
}

/** @internal */
export const CreateStreamBadRequestError$inboundSchema: z.ZodType<
  CreateStreamBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new CreateStreamBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type CreateStreamBadRequestError$Outbound = {
  success: boolean;
  error: string;
};

/** @internal */
export const CreateStreamBadRequestError$outboundSchema: z.ZodType<
  CreateStreamBadRequestError$Outbound,
  z.ZodTypeDef,
  CreateStreamBadRequestError
> = z.instanceof(CreateStreamBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateStreamBadRequestError$ {
  /** @deprecated use `CreateStreamBadRequestError$inboundSchema` instead. */
  export const inboundSchema = CreateStreamBadRequestError$inboundSchema;
  /** @deprecated use `CreateStreamBadRequestError$outboundSchema` instead. */
  export const outboundSchema = CreateStreamBadRequestError$outboundSchema;
  /** @deprecated use `CreateStreamBadRequestError$Outbound` instead. */
  export type Outbound = CreateStreamBadRequestError$Outbound;
}
