/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DaydreamTestError } from "./daydreamtesterror.js";

/**
 * Default Response
 */
export type DeleteStreamInternalServerErrorData = {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;
};

/**
 * Default Response
 */
export class DeleteStreamInternalServerError extends DaydreamTestError {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DeleteStreamInternalServerErrorData;

  constructor(
    err: DeleteStreamInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;

    this.name = "DeleteStreamInternalServerError";
  }
}

/**
 * Default Response
 */
export type DeleteStreamNotFoundErrorData = {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;
};

/**
 * Default Response
 */
export class DeleteStreamNotFoundError extends DaydreamTestError {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DeleteStreamNotFoundErrorData;

  constructor(
    err: DeleteStreamNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;

    this.name = "DeleteStreamNotFoundError";
  }
}

/** @internal */
export const DeleteStreamInternalServerError$inboundSchema: z.ZodType<
  DeleteStreamInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DeleteStreamInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DeleteStreamInternalServerError$Outbound = {
  success: boolean;
  error: string;
};

/** @internal */
export const DeleteStreamInternalServerError$outboundSchema: z.ZodType<
  DeleteStreamInternalServerError$Outbound,
  z.ZodTypeDef,
  DeleteStreamInternalServerError
> = z.instanceof(DeleteStreamInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteStreamInternalServerError$ {
  /** @deprecated use `DeleteStreamInternalServerError$inboundSchema` instead. */
  export const inboundSchema = DeleteStreamInternalServerError$inboundSchema;
  /** @deprecated use `DeleteStreamInternalServerError$outboundSchema` instead. */
  export const outboundSchema = DeleteStreamInternalServerError$outboundSchema;
  /** @deprecated use `DeleteStreamInternalServerError$Outbound` instead. */
  export type Outbound = DeleteStreamInternalServerError$Outbound;
}

/** @internal */
export const DeleteStreamNotFoundError$inboundSchema: z.ZodType<
  DeleteStreamNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DeleteStreamNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DeleteStreamNotFoundError$Outbound = {
  success: boolean;
  error: string;
};

/** @internal */
export const DeleteStreamNotFoundError$outboundSchema: z.ZodType<
  DeleteStreamNotFoundError$Outbound,
  z.ZodTypeDef,
  DeleteStreamNotFoundError
> = z.instanceof(DeleteStreamNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    success: z.boolean(),
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteStreamNotFoundError$ {
  /** @deprecated use `DeleteStreamNotFoundError$inboundSchema` instead. */
  export const inboundSchema = DeleteStreamNotFoundError$inboundSchema;
  /** @deprecated use `DeleteStreamNotFoundError$outboundSchema` instead. */
  export const outboundSchema = DeleteStreamNotFoundError$outboundSchema;
  /** @deprecated use `DeleteStreamNotFoundError$Outbound` instead. */
  export type Outbound = DeleteStreamNotFoundError$Outbound;
}
