/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { DaydreamTestError } from "./daydreamtesterror.js";

/**
 * Default Response
 */
export type GetStreamByIdInternalServerErrorData = {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;
};

/**
 * Default Response
 */
export class GetStreamByIdInternalServerError extends DaydreamTestError {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetStreamByIdInternalServerErrorData;

  constructor(
    err: GetStreamByIdInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;

    this.name = "GetStreamByIdInternalServerError";
  }
}

/**
 * Default Response
 */
export type GetStreamByIdNotFoundErrorData = {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;
};

/**
 * Default Response
 */
export class GetStreamByIdNotFoundError extends DaydreamTestError {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetStreamByIdNotFoundErrorData;

  constructor(
    err: GetStreamByIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;

    this.name = "GetStreamByIdNotFoundError";
  }
}

/**
 * Default Response
 */
export type GetStreamByIdBadRequestErrorData = {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;
};

/**
 * Default Response
 */
export class GetStreamByIdBadRequestError extends DaydreamTestError {
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Human-readable error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: GetStreamByIdBadRequestErrorData;

  constructor(
    err: GetStreamByIdBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.success = err.success;
    this.error = err.error;

    this.name = "GetStreamByIdBadRequestError";
  }
}

/** @internal */
export const GetStreamByIdInternalServerError$inboundSchema: z.ZodType<
  GetStreamByIdInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetStreamByIdInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetStreamByIdNotFoundError$inboundSchema: z.ZodType<
  GetStreamByIdNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetStreamByIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetStreamByIdBadRequestError$inboundSchema: z.ZodType<
  GetStreamByIdBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetStreamByIdBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
