/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Public } from "./public.js";
import { Streams } from "./streams.js";

export class DaydreamTest extends ClientSDK {
  private _streams?: Streams;
  get streams(): Streams {
    return (this._streams ??= new Streams(this._options));
  }

  private _public?: Public;
  get public(): Public {
    return (this._public ??= new Public(this._options));
  }
}
