/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the daydream-test SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx streamsCreateStream.example.ts
 */

import { DaydreamTest } from "daydream-test";

const daydreamTest = new DaydreamTest({
  bearer: process.env["DAYDREAMTEST_BEARER"] ?? "",
});

async function main() {
  const result = await daydreamTest.streams.createStream();

  console.log(result);
}

main().catch(console.error);
