/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteStreamRequest = {
  /**
   * ID of the stream to delete
   */
  id: string;
};

/**
 * Empty object confirming successful deletion
 */
export type DeleteStreamData = {};

/**
 * Default Response
 */
export type DeleteStreamResponse = {
  /**
   * Whether the stream deletion was successful
   */
  success: boolean;
  /**
   * Empty object confirming successful deletion
   */
  data: DeleteStreamData;
};

/** @internal */
export type DeleteStreamRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteStreamRequest$outboundSchema: z.ZodType<
  DeleteStreamRequest$Outbound,
  z.ZodTypeDef,
  DeleteStreamRequest
> = z.object({
  id: z.string(),
});

export function deleteStreamRequestToJSON(
  deleteStreamRequest: DeleteStreamRequest,
): string {
  return JSON.stringify(
    DeleteStreamRequest$outboundSchema.parse(deleteStreamRequest),
  );
}

/** @internal */
export const DeleteStreamData$inboundSchema: z.ZodType<
  DeleteStreamData,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function deleteStreamDataFromJSON(
  jsonString: string,
): SafeParseResult<DeleteStreamData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteStreamData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteStreamData' from JSON`,
  );
}

/** @internal */
export const DeleteStreamResponse$inboundSchema: z.ZodType<
  DeleteStreamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  data: z.lazy(() => DeleteStreamData$inboundSchema),
});

export function deleteStreamResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteStreamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteStreamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteStreamResponse' from JSON`,
  );
}
