/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetStreamByIdRequest = {
  /**
   * ID of the stream to retrieve
   */
  id: string;
};

/**
 * Default Response
 */
export type GetStreamByIdResponse = {
  /**
   * Unique identifier for the stream
   */
  id: string;
  /**
   * Unique key used for streaming to this endpoint
   */
  streamKey: string;
  /**
   * URL where the processed stream output can be accessed
   */
  outputStreamUrl: string;
  /**
   * Current configuration parameters for the stream pipeline
   */
  pipelineParams: { [k: string]: any };
  /**
   * ISO timestamp when the stream was created
   */
  createdAt: string;
  /**
   * ID of the processing pipeline being used
   */
  pipelineId: string;
  /**
   * Playback ID for accessing the stream output
   */
  outputPlaybackId: string;
  /**
   * Human-readable name of the stream
   */
  name: string;
  /**
   * ID of the user who created this stream
   */
  author: string;
  /**
   * Whether this stream was created from the playground interface
   */
  fromPlayground: boolean;
  /**
   * Gateway server hostname handling this stream
   */
  gatewayHost: string;
  /**
   * Whether this is a smoke test stream
   */
  isSmokeTest: boolean;
  /**
   * WebRTC WHIP URL for stream ingestion
   */
  whipUrl: string;
};

/** @internal */
export type GetStreamByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetStreamByIdRequest$outboundSchema: z.ZodType<
  GetStreamByIdRequest$Outbound,
  z.ZodTypeDef,
  GetStreamByIdRequest
> = z.object({
  id: z.string(),
});

export function getStreamByIdRequestToJSON(
  getStreamByIdRequest: GetStreamByIdRequest,
): string {
  return JSON.stringify(
    GetStreamByIdRequest$outboundSchema.parse(getStreamByIdRequest),
  );
}

/** @internal */
export const GetStreamByIdResponse$inboundSchema: z.ZodType<
  GetStreamByIdResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  stream_key: z.string(),
  output_stream_url: z.string(),
  pipeline_params: z.record(z.any()),
  created_at: z.string(),
  pipeline_id: z.string(),
  output_playback_id: z.string(),
  name: z.string(),
  author: z.string(),
  from_playground: z.boolean(),
  gateway_host: z.string(),
  is_smoke_test: z.boolean(),
  whip_url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "stream_key": "streamKey",
    "output_stream_url": "outputStreamUrl",
    "pipeline_params": "pipelineParams",
    "created_at": "createdAt",
    "pipeline_id": "pipelineId",
    "output_playback_id": "outputPlaybackId",
    "from_playground": "fromPlayground",
    "gateway_host": "gatewayHost",
    "is_smoke_test": "isSmokeTest",
    "whip_url": "whipUrl",
  });
});

export function getStreamByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStreamByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamByIdResponse' from JSON`,
  );
}
