/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetStreamStatusRequest = {
  /**
   * ID of the stream to get status for
   */
  id: string;
};

export type Error2 = {
  errorMessage: string;
  /**
   * Unix time in milliseconds
   */
  errorTime: number;
};

export type PeerConnStats2 = {
  /**
   * Peer connection ID
   */
  id: string;
  /**
   * Total bytes received
   */
  bytesReceived: number;
  /**
   * Total bytes sent
   */
  bytesSent: number;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type TrackStat2 = {
  /**
   * RTP codec type, e.g. 'audio' or 'video'
   */
  type: string;
  jitter: number;
  packetsLost: number;
  packetsReceived: number;
  packetLossPct: number;
  /**
   * Round trip time in nanoseconds
   */
  rtt: number;
  warnings?: Array<string> | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/**
 * Connection quality assessment
 */
export const ConnQuality2 = {
  Good: "good",
  Bad: "bad",
  Unknown: "unknown",
} as const;
/**
 * Connection quality assessment
 */
export type ConnQuality2 = ClosedEnum<typeof ConnQuality2>;

export type Stats2 = {
  peerConnStats: PeerConnStats2;
  trackStats?: Array<TrackStat2> | undefined;
  /**
   * Connection quality assessment
   */
  connQuality: ConnQuality2;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type IngestMetrics2 = {
  stats: Stats2;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type GatewayStatus2 = {
  whepUrl?: string | undefined;
  error?: Error2 | undefined;
  ingestMetrics?: IngestMetrics2 | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type GetStreamStatusData2 = {
  gatewayStatus: GatewayStatus2;
  additionalProperties?: { [k: string]: any } | undefined;
};

export const State = {
  Offline: "OFFLINE",
} as const;
export type State = ClosedEnum<typeof State>;

export type DataOffline = {
  state: State;
  info?: string | undefined;
};

export type OrchestratorInfo = {
  address?: string | undefined;
  url?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type InferenceStatus = {
  pipeline?: string | undefined;
  /**
   * Unix seconds
   */
  startTime?: number | undefined;
  /**
   * Unix seconds
   */
  lastParamsUpdateTime?: number | undefined;
  /**
   * Model/pipeline parameters
   */
  lastParams?: any | undefined;
  lastParamsHash?: string | undefined;
  inputFps?: number | undefined;
  outputFps?: number | undefined;
  /**
   * Unix seconds
   */
  lastInputTime?: number | undefined;
  /**
   * Unix seconds
   */
  lastOutputTime?: number | undefined;
  restartCount?: number | undefined;
  /**
   * Unix seconds
   */
  lastRestartTime?: number | undefined;
  lastRestartLogs?: Array<string> | undefined;
  lastError?: string | null | undefined;
  streamId?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type Error1 = {
  errorMessage: string;
  /**
   * Unix time in milliseconds
   */
  errorTime: number;
};

export type PeerConnStats1 = {
  /**
   * Peer connection ID
   */
  id: string;
  /**
   * Total bytes received
   */
  bytesReceived: number;
  /**
   * Total bytes sent
   */
  bytesSent: number;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type TrackStat1 = {
  /**
   * RTP codec type, e.g. 'audio' or 'video'
   */
  type: string;
  jitter: number;
  packetsLost: number;
  packetsReceived: number;
  packetLossPct: number;
  /**
   * Round trip time in nanoseconds
   */
  rtt: number;
  warnings?: Array<string> | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/**
 * Connection quality assessment
 */
export const ConnQuality1 = {
  Good: "good",
  Bad: "bad",
  Unknown: "unknown",
} as const;
/**
 * Connection quality assessment
 */
export type ConnQuality1 = ClosedEnum<typeof ConnQuality1>;

export type Stats1 = {
  peerConnStats: PeerConnStats1;
  trackStats?: Array<TrackStat1> | undefined;
  /**
   * Connection quality assessment
   */
  connQuality: ConnQuality1;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type IngestMetrics1 = {
  stats: Stats1;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type GatewayStatus1 = {
  whepUrl?: string | undefined;
  error?: Error1 | undefined;
  ingestMetrics?: IngestMetrics1 | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type GetStreamStatusData1 = {
  /**
   * Stream identifier
   */
  streamId: string;
  /**
   * Gateway request identifier
   */
  requestId: string;
  /**
   * Pipeline identifier
   */
  pipelineId: string;
  /**
   * Event type (e.g. 'status')
   */
  type?: string | undefined;
  orchestratorInfo?: OrchestratorInfo | undefined;
  inferenceStatus?: InferenceStatus | undefined;
  gatewayStatus?: GatewayStatus1 | undefined;
  /**
   * Model/pipeline name (if present)
   */
  pipeline?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type Data = GetStreamStatusData1 | DataOffline | GetStreamStatusData2;

/**
 * Default Response
 */
export type GetStreamStatusResponse = {
  success: boolean;
  error?: any | null | undefined;
  data?: GetStreamStatusData1 | DataOffline | GetStreamStatusData2 | undefined;
};

/** @internal */
export type GetStreamStatusRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetStreamStatusRequest$outboundSchema: z.ZodType<
  GetStreamStatusRequest$Outbound,
  z.ZodTypeDef,
  GetStreamStatusRequest
> = z.object({
  id: z.string(),
});

export function getStreamStatusRequestToJSON(
  getStreamStatusRequest: GetStreamStatusRequest,
): string {
  return JSON.stringify(
    GetStreamStatusRequest$outboundSchema.parse(getStreamStatusRequest),
  );
}

/** @internal */
export const Error2$inboundSchema: z.ZodType<Error2, z.ZodTypeDef, unknown> = z
  .object({
    error_message: z.string(),
    error_time: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "error_message": "errorMessage",
      "error_time": "errorTime",
    });
  });

export function error2FromJSON(
  jsonString: string,
): SafeParseResult<Error2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Error2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Error2' from JSON`,
  );
}

/** @internal */
export const PeerConnStats2$inboundSchema: z.ZodType<
  PeerConnStats2,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    ID: z.string(),
    BytesReceived: z.number().int(),
    BytesSent: z.number().int(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "ID": "id",
    "BytesReceived": "bytesReceived",
    "BytesSent": "bytesSent",
  });
});

export function peerConnStats2FromJSON(
  jsonString: string,
): SafeParseResult<PeerConnStats2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PeerConnStats2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PeerConnStats2' from JSON`,
  );
}

/** @internal */
export const TrackStat2$inboundSchema: z.ZodType<
  TrackStat2,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    type: z.string(),
    jitter: z.number(),
    packets_lost: z.number().int(),
    packets_received: z.number().int(),
    packet_loss_pct: z.number(),
    rtt: z.number(),
    warnings: z.array(z.string()).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "packets_lost": "packetsLost",
    "packets_received": "packetsReceived",
    "packet_loss_pct": "packetLossPct",
  });
});

export function trackStat2FromJSON(
  jsonString: string,
): SafeParseResult<TrackStat2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TrackStat2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TrackStat2' from JSON`,
  );
}

/** @internal */
export const ConnQuality2$inboundSchema: z.ZodNativeEnum<typeof ConnQuality2> =
  z.nativeEnum(ConnQuality2);

/** @internal */
export const Stats2$inboundSchema: z.ZodType<Stats2, z.ZodTypeDef, unknown> =
  collectExtraKeys$(
    z.object({
      peer_conn_stats: z.lazy(() => PeerConnStats2$inboundSchema),
      track_stats: z.array(z.lazy(() => TrackStat2$inboundSchema)).optional(),
      conn_quality: ConnQuality2$inboundSchema,
    }).catchall(z.any()),
    "additionalProperties",
    true,
  ).transform((v) => {
    return remap$(v, {
      "peer_conn_stats": "peerConnStats",
      "track_stats": "trackStats",
      "conn_quality": "connQuality",
    });
  });

export function stats2FromJSON(
  jsonString: string,
): SafeParseResult<Stats2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Stats2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Stats2' from JSON`,
  );
}

/** @internal */
export const IngestMetrics2$inboundSchema: z.ZodType<
  IngestMetrics2,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    stats: z.lazy(() => Stats2$inboundSchema),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

export function ingestMetrics2FromJSON(
  jsonString: string,
): SafeParseResult<IngestMetrics2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestMetrics2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestMetrics2' from JSON`,
  );
}

/** @internal */
export const GatewayStatus2$inboundSchema: z.ZodType<
  GatewayStatus2,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    whep_url: z.string().optional(),
    error: z.lazy(() => Error2$inboundSchema).optional(),
    ingest_metrics: z.lazy(() => IngestMetrics2$inboundSchema).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "whep_url": "whepUrl",
    "ingest_metrics": "ingestMetrics",
  });
});

export function gatewayStatus2FromJSON(
  jsonString: string,
): SafeParseResult<GatewayStatus2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GatewayStatus2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GatewayStatus2' from JSON`,
  );
}

/** @internal */
export const GetStreamStatusData2$inboundSchema: z.ZodType<
  GetStreamStatusData2,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    gateway_status: z.lazy(() => GatewayStatus2$inboundSchema),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "gateway_status": "gatewayStatus",
  });
});

export function getStreamStatusData2FromJSON(
  jsonString: string,
): SafeParseResult<GetStreamStatusData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamStatusData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamStatusData2' from JSON`,
  );
}

/** @internal */
export const State$inboundSchema: z.ZodNativeEnum<typeof State> = z.nativeEnum(
  State,
);

/** @internal */
export const DataOffline$inboundSchema: z.ZodType<
  DataOffline,
  z.ZodTypeDef,
  unknown
> = z.object({
  state: State$inboundSchema,
  info: z.string().optional(),
});

export function dataOfflineFromJSON(
  jsonString: string,
): SafeParseResult<DataOffline, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataOffline$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataOffline' from JSON`,
  );
}

/** @internal */
export const OrchestratorInfo$inboundSchema: z.ZodType<
  OrchestratorInfo,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    address: z.string().optional(),
    url: z.string().optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

export function orchestratorInfoFromJSON(
  jsonString: string,
): SafeParseResult<OrchestratorInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrchestratorInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrchestratorInfo' from JSON`,
  );
}

/** @internal */
export const InferenceStatus$inboundSchema: z.ZodType<
  InferenceStatus,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    pipeline: z.string().optional(),
    start_time: z.number().optional(),
    last_params_update_time: z.number().optional(),
    last_params: z.any().optional(),
    last_params_hash: z.string().optional(),
    input_fps: z.number().optional(),
    output_fps: z.number().optional(),
    last_input_time: z.number().optional(),
    last_output_time: z.number().optional(),
    restart_count: z.number().int().optional(),
    last_restart_time: z.number().optional(),
    last_restart_logs: z.array(z.string()).optional(),
    last_error: z.nullable(z.string()).optional(),
    stream_id: z.string().optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "start_time": "startTime",
    "last_params_update_time": "lastParamsUpdateTime",
    "last_params": "lastParams",
    "last_params_hash": "lastParamsHash",
    "input_fps": "inputFps",
    "output_fps": "outputFps",
    "last_input_time": "lastInputTime",
    "last_output_time": "lastOutputTime",
    "restart_count": "restartCount",
    "last_restart_time": "lastRestartTime",
    "last_restart_logs": "lastRestartLogs",
    "last_error": "lastError",
    "stream_id": "streamId",
  });
});

export function inferenceStatusFromJSON(
  jsonString: string,
): SafeParseResult<InferenceStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InferenceStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InferenceStatus' from JSON`,
  );
}

/** @internal */
export const Error1$inboundSchema: z.ZodType<Error1, z.ZodTypeDef, unknown> = z
  .object({
    error_message: z.string(),
    error_time: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "error_message": "errorMessage",
      "error_time": "errorTime",
    });
  });

export function error1FromJSON(
  jsonString: string,
): SafeParseResult<Error1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Error1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Error1' from JSON`,
  );
}

/** @internal */
export const PeerConnStats1$inboundSchema: z.ZodType<
  PeerConnStats1,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    ID: z.string(),
    BytesReceived: z.number().int(),
    BytesSent: z.number().int(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "ID": "id",
    "BytesReceived": "bytesReceived",
    "BytesSent": "bytesSent",
  });
});

export function peerConnStats1FromJSON(
  jsonString: string,
): SafeParseResult<PeerConnStats1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PeerConnStats1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PeerConnStats1' from JSON`,
  );
}

/** @internal */
export const TrackStat1$inboundSchema: z.ZodType<
  TrackStat1,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    type: z.string(),
    jitter: z.number(),
    packets_lost: z.number().int(),
    packets_received: z.number().int(),
    packet_loss_pct: z.number(),
    rtt: z.number(),
    warnings: z.array(z.string()).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "packets_lost": "packetsLost",
    "packets_received": "packetsReceived",
    "packet_loss_pct": "packetLossPct",
  });
});

export function trackStat1FromJSON(
  jsonString: string,
): SafeParseResult<TrackStat1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TrackStat1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TrackStat1' from JSON`,
  );
}

/** @internal */
export const ConnQuality1$inboundSchema: z.ZodNativeEnum<typeof ConnQuality1> =
  z.nativeEnum(ConnQuality1);

/** @internal */
export const Stats1$inboundSchema: z.ZodType<Stats1, z.ZodTypeDef, unknown> =
  collectExtraKeys$(
    z.object({
      peer_conn_stats: z.lazy(() => PeerConnStats1$inboundSchema),
      track_stats: z.array(z.lazy(() => TrackStat1$inboundSchema)).optional(),
      conn_quality: ConnQuality1$inboundSchema,
    }).catchall(z.any()),
    "additionalProperties",
    true,
  ).transform((v) => {
    return remap$(v, {
      "peer_conn_stats": "peerConnStats",
      "track_stats": "trackStats",
      "conn_quality": "connQuality",
    });
  });

export function stats1FromJSON(
  jsonString: string,
): SafeParseResult<Stats1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Stats1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Stats1' from JSON`,
  );
}

/** @internal */
export const IngestMetrics1$inboundSchema: z.ZodType<
  IngestMetrics1,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    stats: z.lazy(() => Stats1$inboundSchema),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

export function ingestMetrics1FromJSON(
  jsonString: string,
): SafeParseResult<IngestMetrics1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestMetrics1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestMetrics1' from JSON`,
  );
}

/** @internal */
export const GatewayStatus1$inboundSchema: z.ZodType<
  GatewayStatus1,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    whep_url: z.string().optional(),
    error: z.lazy(() => Error1$inboundSchema).optional(),
    ingest_metrics: z.lazy(() => IngestMetrics1$inboundSchema).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "whep_url": "whepUrl",
    "ingest_metrics": "ingestMetrics",
  });
});

export function gatewayStatus1FromJSON(
  jsonString: string,
): SafeParseResult<GatewayStatus1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GatewayStatus1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GatewayStatus1' from JSON`,
  );
}

/** @internal */
export const GetStreamStatusData1$inboundSchema: z.ZodType<
  GetStreamStatusData1,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    stream_id: z.string(),
    request_id: z.string(),
    pipeline_id: z.string(),
    type: z.string().optional(),
    orchestrator_info: z.lazy(() => OrchestratorInfo$inboundSchema).optional(),
    inference_status: z.lazy(() => InferenceStatus$inboundSchema).optional(),
    gateway_status: z.lazy(() => GatewayStatus1$inboundSchema).optional(),
    pipeline: z.string().optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "stream_id": "streamId",
    "request_id": "requestId",
    "pipeline_id": "pipelineId",
    "orchestrator_info": "orchestratorInfo",
    "inference_status": "inferenceStatus",
    "gateway_status": "gatewayStatus",
  });
});

export function getStreamStatusData1FromJSON(
  jsonString: string,
): SafeParseResult<GetStreamStatusData1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamStatusData1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamStatusData1' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .union([
    z.lazy(() => GetStreamStatusData1$inboundSchema),
    z.lazy(() => DataOffline$inboundSchema),
    z.lazy(() => GetStreamStatusData2$inboundSchema),
  ]);

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const GetStreamStatusResponse$inboundSchema: z.ZodType<
  GetStreamStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  error: z.nullable(z.any()).optional(),
  data: z.union([
    z.lazy(() => GetStreamStatusData1$inboundSchema),
    z.lazy(() => DataOffline$inboundSchema),
    z.lazy(() => GetStreamStatusData2$inboundSchema),
  ]).optional(),
});

export function getStreamStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStreamStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStreamStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStreamStatusResponse' from JSON`,
  );
}
