/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export type Z = {
  type: "z";
  zSpecificFieldA: number;
  zSpecificFieldB: string;
  zSpecificFieldC: number;
};

export type Y = {
  type: "y";
  ySpecificFieldA: string;
};

export type X = {
  type: "x";
  xSpecificFieldA: number;
  xSpecificFieldB: string;
};

export type TestStreamRequest = X | Y | Z;

/**
 * Default Response
 */
export const Okay = {
  Okay: "okay",
} as const;
/**
 * Default Response
 */
export type Okay = ClosedEnum<typeof Okay>;

/** @internal */
export type Z$Outbound = {
  type: "z";
  zSpecificFieldA: number;
  zSpecificFieldB: string;
  zSpecificFieldC: number;
};

/** @internal */
export const Z$outboundSchema: z.ZodType<Z$Outbound, z.ZodTypeDef, Z> = z
  .object({
    type: z.literal("z"),
    zSpecificFieldA: z.number(),
    zSpecificFieldB: z.string(),
    zSpecificFieldC: z.number(),
  });

export function zToJSON(z: Z): string {
  return JSON.stringify(Z$outboundSchema.parse(z));
}

/** @internal */
export type Y$Outbound = {
  type: "y";
  ySpecificFieldA: string;
};

/** @internal */
export const Y$outboundSchema: z.ZodType<Y$Outbound, z.ZodTypeDef, Y> = z
  .object({
    type: z.literal("y"),
    ySpecificFieldA: z.string(),
  });

export function yToJSON(y: Y): string {
  return JSON.stringify(Y$outboundSchema.parse(y));
}

/** @internal */
export type X$Outbound = {
  type: "x";
  xSpecificFieldA: number;
  xSpecificFieldB: string;
};

/** @internal */
export const X$outboundSchema: z.ZodType<X$Outbound, z.ZodTypeDef, X> = z
  .object({
    type: z.literal("x"),
    xSpecificFieldA: z.number(),
    xSpecificFieldB: z.string(),
  });

export function xToJSON(x: X): string {
  return JSON.stringify(X$outboundSchema.parse(x));
}

/** @internal */
export type TestStreamRequest$Outbound = X$Outbound | Y$Outbound | Z$Outbound;

/** @internal */
export const TestStreamRequest$outboundSchema: z.ZodType<
  TestStreamRequest$Outbound,
  z.ZodTypeDef,
  TestStreamRequest
> = z.union([
  z.lazy(() => X$outboundSchema),
  z.lazy(() => Y$outboundSchema),
  z.lazy(() => Z$outboundSchema),
]);

export function testStreamRequestToJSON(
  testStreamRequest: TestStreamRequest,
): string {
  return JSON.stringify(
    TestStreamRequest$outboundSchema.parse(testStreamRequest),
  );
}

/** @internal */
export const Okay$inboundSchema: z.ZodNativeEnum<typeof Okay> = z.nativeEnum(
  Okay,
);
